### PR TITLE
Upgrade nix to 0.28

### PR DESCRIPTION
**Pull request by sunshowers**
Thanks for maintaining this crate! Sending a PR to update nix to the latest version, so it picks up (in particular) https://github.com/nix-rust/nix/pull/2275.

Thanks!

### CODE REVIEW

**Review by andreacorbellini — CHANGES_REQUESTED** [review]
Thanks for submitting this! It looks like it's failing to build on Linux due to some missing `Option`, could you please fix that?

**Comment by sunshowers** [comment]
Whoops, haha -- should have tested there! I usually do my dev on Linux, but was on illumos while debugging this.

**Comment by andreacorbellini** [comment]
Sorry, looks like the CI is failing due to linting. If you run `cargo fmt` it should fix the problem. Thanks!

**Comment by sunshowers** [comment]
My bad! I was editing using raw vim rather than vscode for $reasons.

Would you be willing to change the "require approval" setting to make it so that it only applies to users not new to GitHub?

image

**Comment by sunshowers** [comment]
Thank you! Wondering if you can get a release out soon.

**Comment by andreacorbellini** [comment]
Hi, yes, these days I'm very time constrained but I'll try to get it out
this weekend.

**Comment by andreacorbellini** [comment]
Version 0.1.3 is now published with your changes: https://crates.io/crates/atomic-write-file/0.1.3. Enjoy, and thanks again for your contribution!

**Comment by sunshowers** [comment]
Appreciate it! Thanks again for being so responsive :)

**Pull request merged**
